pipeline:
  name: Build Python App
  identifier: Build_Python_App
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.mygit
        repoName: python
        build: <+input>
  stages:
    - stage:
        name: Build and Test
        identifier: Build_and_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      pip install --upgrade pip
                      pip install -r requirements.txt
                      pip install -r test-requirements.txt
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.dockerregistry
                    repo: hindusreedunaboyina/python
                    tags:
                      - latest
              - step:
                  type: Run
                  name: run tests
                  identifier: run_tests
                  spec:
                    shell: Bash
                    command: pytest tests/
