pipeline:
  name: my-python-ci
  identifier: mypythonci
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.mygit
        repoName: python
        build: <+input>
  stages:
    - stage:
        name: Build and Setup Environment
        identifier: Build_and_Setup_Environment
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Virtual-Environment-Setup
                  identifier: VirtualEnvironmentSetup
                  spec:
                    shell: Bash
                    command: |-
                      rm -rf venv
                      pip install virtualenv
                      python3 -m venv venv
                      source venv/bin/activate
                  description: setting up virtual environment locally for python application
              - step:
                  type: Run
                  name: Install Dependencies
                  identifier: Install_Dependencies
                  spec:
                    shell: Bash
                    command: |-
                      pip install -r requirements.txt
                      pip install -r test-requirements.txt
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: testing
                  identifier: testing
                  spec:
                    shell: Bash
                    command: pytest tests/
