pipeline:
  name: python
  identifier: python
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.mygit
        repoName: python
        build: <+input>
  stages:
    - stage:
        name: python_build
        identifier: python_build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      python -m venv venv
                      source venv/bin/activate
                      pip install -r requirements.txt
                      python setup.py sdist
              - step:
                  type: Run
                  name: Run_2
                  identifier: Run_2
                  spec:
                    shell: Bash
                    command: |-
                      ls -l dist/
                      chmod +r dist/dronedemo-1.0.tar.gz
                      chmod 644 dist/dronedemo-1.0.tar.gz
    - stage:
        name: Upload Tar to Artifactory
        identifier: Upload_Tar_to_Artifactory
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: |-
                      curl -u "{{secrets.ARTIFACTORY_USER}}:{{secrets.ARTIFACTORY_API_KEY}}" \
                        -T "dist/dronedemo-1.0.tar.gz" \
                        "https://hindusree444.jfrog.io/artifactory/harnessarti-generic-local/my-path/dronedemo-1.0.tar.gz"
